"use client";
// SpeciesAISummary — fetches the cached or live Claude-generated
// summary from /api/species/[id]/summary. Renders nothing while
// the request is in-flight (no skeleton — the rest of the page is
// already busy enough on first paint).

import { useEffect, useState } from "react";

export default function SpeciesAISummary({ speciesId }) {
  const [data, setData] = useState(null);
  const [err, setErr] = useState(null);

  useEffect(() => {
    if (!speciesId) return;
    let cancelled = false;
    (async () => {
      try {
        const r = await fetch(`/api/species/${speciesId}/summary`);
        const json = await r.json();
        if (cancelled) return;
        if (!r.ok) throw new Error(json?.error || `HTTP ${r.status}`);
        setData(json);
      } catch (e) {
        if (!cancelled) setErr(e?.message || "Could not load");
      }
    })();
    return () => { cancelled = true; };
  }, [speciesId]);

  if (err) return null;
  if (!data) return null;
  if (!data.body_md) return null;

  return (
    <section
      style={{
        marginTop: 14,
        padding: 18,
        background:
          "linear-gradient(135deg, rgba(83,74,183,0.05) 0%, rgba(245,166,35,0.04) 100%), var(--gx-surface)",
        border: "1px solid color-mix(in srgb, var(--gx-accent-violet) 18%, var(--gx-border))",
        borderRadius: "var(--gx-radius-4)",
        position: "relative",
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: 8,
        }}
      >
        <div style={{
          fontSize: 10,
          fontWeight: 700,
          letterSpacing: 1.5,
          textTransform: "uppercase",
          color: "var(--gx-accent-violet)",
          display: "inline-flex",
          alignItems: "center",
          gap: 6,
        }}>
          {data.ai === false ? "📝 Generated summary" : "✨ What we know"}
        </div>
        <span style={{ fontSize: 9, color: "var(--gx-ink-muted)", fontFamily: "var(--gx-font-mono)" }}>
          {data.cached ? "cached" : data.ai ? data.model : "fallback"}
        </span>
      </div>
      <div
        style={{
          fontSize: 14,
          lineHeight: 1.65,
          color: "var(--gx-ink)",
          whiteSpace: "pre-wrap",
          fontFamily: "var(--gx-font-serif)",
        }}
      >
        {renderInlineMarkdown(data.body_md)}
      </div>
      {data.ai !== false && (
        <div style={{ marginTop: 10, fontSize: 9, color: "var(--gx-ink-muted)", fontStyle: "italic" }}>
          Generated by Claude from indexed publications + atlas signal.
          Verify before citing.
        </div>
      )}
    </section>
  );
}

// Minimal Markdown-ish renderer: italic (*text*) + bold (**text**).
// No HTML, no link rewriting — Claude was instructed to write plain prose.
function renderInlineMarkdown(text) {
  if (!text) return null;
  const parts = [];
  // Split by **bold** first
  const boldRe = /\*\*(.+?)\*\*/g;
  let lastIdx = 0;
  let m;
  while ((m = boldRe.exec(text)) !== null) {
    parts.push({ kind: "plain", text: text.slice(lastIdx, m.index) });
    parts.push({ kind: "bold",  text: m[1] });
    lastIdx = m.index + m[0].length;
  }
  parts.push({ kind: "plain", text: text.slice(lastIdx) });

  return parts.flatMap((p, i) => {
    if (p.kind === "bold") {
      return (
        <strong key={`b-${i}`} style={{ color: "var(--gx-ink)" }}>
          {renderItalics(p.text, `b-${i}`)}
        </strong>
      );
    }
    return renderItalics(p.text, `p-${i}`);
  });
}

function renderItalics(text, parentKey) {
  if (!text) return null;
  const italRe = /\*([^*]+)\*/g;
  const out = [];
  let lastIdx = 0;
  let m;
  while ((m = italRe.exec(text)) !== null) {
    if (m.index > lastIdx) out.push(text.slice(lastIdx, m.index));
    out.push(<em key={`${parentKey}-i-${m.index}`}>{m[1]}</em>);
    lastIdx = m.index + m[0].length;
  }
  if (lastIdx < text.length) out.push(text.slice(lastIdx));
  return out;
}
