/**
 * ISO-3166-1 alpha-2 → human-readable country name. Covers every code in
 * lib/countryCentroids.js. Used by the country dashboard, atlas chips and
 * any place where "TR" should read as "Turkey".
 */
export const COUNTRY_NAMES = {
  TR: "Turkey",
  IR: "Iran",
  ZA: "South Africa",
  US: "United States",
  GR: "Greece",
  CL: "Chile",
  ES: "Spain",
  CN: "China",
  MX: "Mexico",
  PT: "Portugal",
  GE: "Georgia",
  IN: "India",
  AF: "Afghanistan",
  BR: "Brazil",
  ET: "Ethiopia",
  KZ: "Kazakhstan",
  PE: "Peru",
  AM: "Armenia",
  CO: "Colombia",
  IQ: "Iraq",
  MA: "Morocco",
  BG: "Bulgaria",
  MG: "Madagascar",
  AR: "Argentina",
  UZ: "Uzbekistan",
  IL: "Israel",
  SY: "Syria",
  AU: "Australia",
  NZ: "New Zealand",
  IT: "Italy",
  NP: "Nepal",
  JP: "Japan",
  FR: "France",
  GB: "United Kingdom",
  DE: "Germany",
  RU: "Russia",
  CA: "Canada",
  CH: "Switzerland",
  AT: "Austria",
  BE: "Belgium",
  NL: "Netherlands",
  PL: "Poland",
  SE: "Sweden",
  NO: "Norway",
  FI: "Finland",
  DK: "Denmark",
  HU: "Hungary",
  RO: "Romania",
  CZ: "Czechia",
  SK: "Slovakia",
  HR: "Croatia",
  RS: "Serbia",
  AL: "Albania",
  MK: "North Macedonia",
  BA: "Bosnia & Herzegovina",
  SI: "Slovenia",
  UA: "Ukraine",
  IE: "Ireland",
  CY: "Cyprus",
  LB: "Lebanon",
  JO: "Jordan",
  SA: "Saudi Arabia",
  EG: "Egypt",
  TN: "Tunisia",
  DZ: "Algeria",
  LY: "Libya",
  SD: "Sudan",
  KE: "Kenya",
  TZ: "Tanzania",
  UG: "Uganda",
  NG: "Nigeria",
  NA: "Namibia",
  BW: "Botswana",
  ZW: "Zimbabwe",
  ZM: "Zambia",
  MZ: "Mozambique",
  AO: "Angola",
  TH: "Thailand",
  VN: "Vietnam",
  ID: "Indonesia",
  PH: "Philippines",
  MY: "Malaysia",
  KR: "South Korea",
  PK: "Pakistan",
  EC: "Ecuador",
  BO: "Bolivia",
  VE: "Venezuela",
  PY: "Paraguay",
  UY: "Uruguay",
  MC: "Monaco",
  NC: "New Caledonia",
  PS: "Palestine",
  IM: "Isle of Man",
  AD: "Andorra",
  LU: "Luxembourg",
  EE: "Estonia",
  LT: "Lithuania",
  LV: "Latvia",
  IS: "Iceland",
  MT: "Malta",
  AE: "United Arab Emirates",
  OM: "Oman",
  YE: "Yemen",
  QA: "Qatar",
  BH: "Bahrain",
  KW: "Kuwait",
  BY: "Belarus",
};

export function countryName(iso2) {
  if (!iso2) return null;
  return COUNTRY_NAMES[iso2.toUpperCase()] || iso2.toUpperCase();
}
